### ISSUE TITLE
yolov5 weights link failed

### ISSUE THREAD

**Issue by jcsh4326** [HowieMa/DeepSORT_YOLOv5_Pytorch#1]
Hi, I click the link of yolov5 weights, it seems in a google drive trash.
But then I realized it must be an official weight offered by glenn-jocher.
So, maybe you can change the link to a workable one or link to the yolov5?

**Comment by HowieMa** [comment]
Hi, thank you for your suggestion. I have updated the link to the official site of yolov5, in case they change the link of google drive in the future.
